### ISSUE TITLE
Mono Icon stays dark in dark mode

### ISSUE THREAD

**Issue by davisstu** [david-kuehn/casita#6]
The mono icon (a welcome addition) remains black in dark mode - it should revert to white at that point.

MacOS Big Sur 11.2RC1

**Comment by david-kuehn** [comment]
Thanks for pointing this out - fixed in the latest commit. Interestingly, the color of the icons in the menu bar are not tied to light/dark mode, but rather to the color of the wallpaper. I tested with both light-colored and dark-colored backgrounds and got a white icon on dark and a black icon on light; let me know if you have different results.

**Comment by davisstu** [comment]
Thanks. You're correct - it's the wallpaper, I realised this after submitting the issue and didn't correct it. But we got there in the end with it.
